name: My First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Welcome message
        run: |
          echo "My first Github Actions Job"
          ls -ltra
          cat README.md

      - name: Genrate Asci Artwork
        run: |
          sudo apt-get install cowsay -y
          cowsay -f dragon "i am dragon" > dragon.txt
          grep -i "dragon" dragon.txt
          cat dragon.txt