name: my first workflow 

on: push 
jobs: 
    first_jop:
        runs-on: ubuntu-latest
        steps:
        - name: checkout Repo
          uses: actions/checkout@v5  
        - name: welcome
          run: |
            echo "abdelkarim"
            ls -ltra
            cat README.md
        - name: Excute bash script
          run: |
            chmod -R +x script.sh
            ./script.sh

            
    

